# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - {label: Phone, name: phone, widget: string, required: false}    
          - {label: Email, name: email, widget: string, required: false}
          - {label: Address, name: address, widget: string, required: false}
          - {label: Latitude, name: latitude, widget: string, required: false}
          - {label: Longitude, name: longitude, widget: string, required: false}
          - {label: Twitter, name: twitter, widget: string, required: false}
          - {label: Facebook, name: facebook, widget: string, required: false}
          - {label: Linkedin, name: linkedin, widget: string, required: false}
          - {label: Instagram, name: instagram, widget: string, required: false}
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - {label: Button Text, name: buttonText, widget: string}
              - {label: Button Url, name: buttonUrl, widget: string}
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string}
              - label: "Footer Nav"
                name: "footerNav"
                widget: "list"
                fields:
                  - {label: Button Text, name: buttonText, widget: string}
                  - {label: Button Url, name: buttonUrl, widget: string}
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - {label: Image, name: image, widget: image}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}

  - name: "pages"
    label: "Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - {label: Featured Image, name: featuredImage, widget: image, required: false}
          - {label: Sub Title, name: subTitle, widget: string, required: false}
          - {label: Title, name: title, widget: string, required: false}
          - {label: Content, name: content, widget: string, required: false}
          - {label: Button Text, name: buttonText, widget: string, required: false}
          - {label: Button Url, name: buttonUrl, widget: string, required: false} 
          - label: "Gallery"
            name: "gallery"
            widget: "object"
            fields:
              - {label: Sub Title, name: subTitle, widget: string}
              - {label: Title, name: title, widget: string}
              - label: "Gallery Images"
                name: "galleryImages"
                widget: "list"
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Title, name: title, widget: string}
          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Sub Title, name: subTitle, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
              - {label: Button Text, name: buttonText, widget: string}
              - {label: Button Url, name: buttonUrl, widget: string}
          - label: "Testimonials"
            name: "testimonials"
            widget: "object"  
            fields: 
              - {label: Title, name: title, widget: string} 
              - label: "Testimonial"
                name: "testimonial"
                widget: "list"  
                fields: 
                  - {label: Title, name: title, widget: string}  
                  - {label: Content, name: content, widget: markdown}
                  - {label: Logo, name: logo, widget: image}
                  - {label: Name, name: name, widget: string}
          - label: "Columns"
            name: "columns"
            widget: "list"
            fields:
              - {label: Left Align, name: leftAlign, widget: boolean, default: true}
              - {label: Image, name: image, widget: image}
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}
              - {label: Button Title, name: buttonTitle, widget: string}
              - {label: Button Url, name: buttonUrl, widget: string}
          - label: "Featured Blog"
            name: "featuredBlog"
            widget: "object"
            fields:
              - {label: Sub Title, name: subTitle, widget: string}
              - {label: Title, name: title, widget: string}
              - label: "Blog Posts"
                name: "blogPosts"
                widget: "list"
                fields:
                  - {label: Top Align, name: topAlign, widget: boolean, default: true}
                  - {label: Image, name: image, widget: image}
                  - {label: Title, name: title, widget: string}
                  - {label: Category, name: category, widget: string}
                  - {label: Author, name: author, widget: string}
                  - {label: Date, name: date, widget: string}
                  - {label: Post Url, name: postUrl, widget: string}

      - file: "content/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {label: Featured Image, name: featuredImage, widget: image, required: false}
          - {label: Sub Title, name: subTitle, widget: string, required: false}
          - {label: Title, name: title, widget: string, required: false}
          - label: "Team Members"
            name: "teamMembers"
            widget: "list"
            fields:
              - {label: Left Align, name: leftAlign, widget: boolean, default: true}
              - {label: Image, name: image, widget: image}
              - {label: Sub Title, name: subTitle, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: "Services"
            name: "services"
            widget: "object"
            fields:
              - {label: Sub Title, name: subTitle, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}
              - label: "Service Items"
                name: "serviceItems"
                widget: "list"
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: content, widget: markdown}
      - file: "content/pages/models.md"
        label: "Models"
        name: "models"
        fields:
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Sub Title, name: subTitle, widget: string}
          - {label: Title, name: title, widget: string}
          - label: "Model Listing"
            name: "modelListing"
            widget: "list"
            fields:
              - {label: Collection, name: collection, widget: relation, collection: 'model', searchFields: ['title'], valueField: 'title'}

  - label: "Model"
    name: "model"
    delete: true # Prevent users from deleting documents in this collection
    editor:
      preview: false
    folder: "content/model"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Featured Image, name: featuredImage, widget: image}
      - {label: Image Thumbnail, name: imageThumbnail, widget: image}
      - {label: First Name, name: firstName, widget: string}
      - {label: Last Name, name: lastName, widget: string}
      - {label: Collection, name: collection, widget: relation, collection: 'model-types', searchFields: ['title'], valueField: 'title'}
      - label: "Model Specs"
        name: "modelSpecs"
        widget: "list"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: content, widget: string}
      - label: "Image Portfolio"
        name: "imagePortfolio"
        widget: "list"
        fields:   
          - {label: Image, name: image, widget: image}

  - name: "model-types"
    label: "Model Types"
    delete: true # Prevent users from deleting documents in this collection
    editor:
      preview: false
    folder: "content/model-types"
    create: true
    fields:
      - {label: Title, name: title, widget: string}







